### PR TITLE
Better readme

### PR DESCRIPTION
**Pull request by HDembinski**
Get badges back, now it works for real

### CODE REVIEW

**Comment by cdeil** [comment]
Did you see status.rst? I removed the badges from the Readme, because that is used for the PyPI front page, and there I don’T think it belongs, status is only for the dev version.

**Comment by HDembinski** [comment]
So what do we do then? I think we need badges on github.

**Comment by HDembinski** [comment]
The readme is the first entry point for people on github. There we want to show that this project is not dead but working well and badges are the way to do it.

I value badges in the readme more than having one file that is consistent between PyPI and github.

**Comment by HDembinski** [comment]
We could also do something smart and remove the badges automatically when the readme is parsed by setup.py. Perhaps that's the way to go.

**Comment by cdeil** [comment]
Actually you and I are probably the only ones that care about these badges.
Note that most users will use and care about the released version, so if they for some reason (i.e. Google) find the Github page and see a successful or broken build status for master, it's not really helpful.

My suggestion would be to put it as it was, i.e. have the badges in status.rst.

If you really want them in the README for some reason, you have to write the `long_description` on the `setup` call (what PyPI shows) somehow differently, e.g. put it as a multi-line string in the setup.py.

**Comment by cdeil** [comment]
@HDembinski - How should we resolve this discussion / PR?

I've had projects with badges in README and shown on PyPI before, and it was always a mess because the badges showed the CI status for the dev version, sometimes as broken, but were displayed on PyPI for a stable version that was perfectly fine.

What we currently have is nice, no? https://pypi.org/project/iminuit/

Suggest to keep as-is, or add one line to the README for developers: "For the continuous integration status of iminuit, see the `status.rst` file on Github." if you think that's useful.

Changing the way we set `long_description` and making it different from the README is extra effort / complexity for little gain, no?

**Comment by HDembinski** [comment]
Let's close the request. I was thinking of writing some code that parses the README.rst in setup.py and removes the badges tables, but I don't have time to work on it and I can also make a new PR when I ever feel that this is really important.

**Comment by cdeil** [comment]
> I was thinking of writing some code that parses the README.rst in setup.py and removes the badges tables

IMO setup.py shouldn't contain such code. Even if unlikely, it has the potential to break things e.g. if someone doesn't know about it and edits the README in a few years and then just sees on https://pypi.org/project/iminuit/ that the output is garbled after making a release.

**Comment by HDembinski** [comment]
And I don't like that we don't have badges on github anymore, which I consider to be very useful. What other solution would you propose to get badges on github, while keeping the readme constistent between PyPI and github?

**Comment by cdeil** [comment]
The badges are visible on github, you just have to do one click: https://github.com/iminuit/iminuit/blob/master/status.rst

IMO one click is acceptable for the very few people that very rarely need to look at this.

**Pull request closed without merging**
