### PR TITLE
fixed failing test_drawcontour

### PR DESCRIPTION
**Pull request by HDembinski**
The v array used to label the contours. It was not in sync with the bound argument of the call to self.contour(...) which generates the contours. This is now fixed.

### CODE REVIEW

**Comment by cdeil** [comment]
Thanks!

**Comment by HDembinski** [comment]
@cdeil Cool, thank you! I am honored and will use this permission responsibly.

**Comment by alexpearce** [comment]
No problem at all @cdeil. Thanks a lot for the contributions @HDembinski!

**Comment by HDembinski** [comment]
@alexpearce No problem that one was easy :), now I am looking into updating Minuit code from ROOT, this is hard.

**Pull request merged**
